server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    disable_symlinks off;

    location /storage {
        alias /var/www/storage/app/public;
        add_header Access-Control-Allow-Origin *;
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}